<?xml version="1.0" encoding="UTF-8"?><testrun name="ZipCodePreProcessTest" project="com.rui.zipcode" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="com.rui.zipcode.ZipCodePreProcessTest" time="0.0">
    <testcase name="validationCatchInvalidLength" classname="com.rui.zipcode.ZipCodePreProcessTest" time="0.0"/>
    <testcase name="generateZipCodeArrayTest" classname="com.rui.zipcode.ZipCodePreProcessTest" time="0.0"/>
    <testcase name="validationCatchMissingValue" classname="com.rui.zipcode.ZipCodePreProcessTest" time="0.0"/>
    <testcase name="validation" classname="com.rui.zipcode.ZipCodePreProcessTest" time="0.0"/>
    <testcase name="validationCatchInvalidPair" classname="com.rui.zipcode.ZipCodePreProcessTest" time="0.0">
      <failure>java.lang.AssertionError: Expected exception: java.lang.IllegalArgumentException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

</failure>
    </testcase>
  </testsuite>
</testrun>
